version: "3.9"

networks:
  traefik:
    external: true

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    env_file:
      - ../ops/.env.local
      - ./app.env
    networks: [traefik]
    volumes:
      - ./configuration.yml:/config/configuration.yml:ro
      - ./users.yaml:/config/users.yaml:ro
      - ./secrets:/secrets:ro

    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik

      # ---------- Middlewares ----------
      # "/" → "/authelia/"
      - traefik.http.middlewares.authelia-root-redirect.redirectregex.regex=^/$
      - traefik.http.middlewares.authelia-root-redirect.redirectregex.replacement=/authelia/
      - traefik.http.middlewares.authelia-root-redirect.redirectregex.permanent=true

      # "/authelia" → "/authelia/"
      - traefik.http.middlewares.authelia-add-slash.redirectregex.regex=^/authelia$
      - traefik.http.middlewares.authelia-add-slash.redirectregex.replacement=/authelia/
      - traefik.http.middlewares.authelia-add-slash.redirectregex.permanent=true

      # ---------- Services (one per host) ----------
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.services.authelia-abs.loadbalancer.server.port=9091
      - traefik.http.services.authelia-ollama.loadbalancer.server.port=9091

      # ---------- AUTH_HOST (serve whole host) ----------
      - traefik.http.routers.authelia-host.rule=Host(`${AUTH_HOST}`) && PathPrefix(`/`)
      - traefik.http.routers.authelia-host.entrypoints=websecure
      - traefik.http.routers.authelia-host.tls.certresolver=cloudflare
      - traefik.http.routers.authelia-host.middlewares=authelia-root-redirect,authelia-add-slash,secure-headers@docker
      - traefik.http.routers.authelia-host.service=authelia

      # ---------- AUDIOBOOKSHELF_HOST under /authelia ----------
      - traefik.http.routers.authelia-abs.rule=Host(`${AUDIOBOOKSHELF_HOST}`) && PathPrefix(`/authelia`)
      - traefik.http.routers.authelia-abs.entrypoints=websecure
      - traefik.http.routers.authelia-abs.tls.certresolver=cloudflare
      - traefik.http.routers.authelia-abs.middlewares=authelia-add-slash,secure-headers@docker
      - traefik.http.routers.authelia-abs.service=authelia-abs

      # ---------- OLLAMA_HOST under /authelia ----------
      - traefik.http.routers.authelia-ollama.rule=Host(`${OLLAMA_HOST}`) && PathPrefix(`/authelia`)
      - traefik.http.routers.authelia-ollama.entrypoints=websecure
      - traefik.http.routers.authelia-ollama.tls.certresolver=cloudflare
      - traefik.http.routers.authelia-ollama.middlewares=authelia-add-slash,secure-headers@docker
      - traefik.http.routers.authelia-ollama.service=authelia-ollama

      - traefik.http.routers.authelia-nextcloud.rule=Host(`nextcloud.neovara.uk`) && PathPrefix(`/authelia`)
      - traefik.http.routers.authelia-nextcloud.entrypoints=websecure
      - traefik.http.routers.authelia-nextcloud.tls.certresolver=cloudflare
      - traefik.http.routers.authelia-nextcloud.middlewares=authelia-add-slash,secure-headers@docker
      - traefik.http.routers.authelia-nextcloud.service=authelia-nextcloud
      - traefik.http.services.authelia-nextcloud.loadbalancer.server.port=9091
