log:
  level: info

server:
  address: "tcp://0.0.0.0:9091/authelia"
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"
        authn_strategies:
          - name: "CookieSession"

session:
  cookies:
    - domain: {{mustEnv "AUDIOBOOKSHELF_HOST"}}
      authelia_url: 'https://{{mustEnv "AUDIOBOOKSHELF_HOST"}}/authelia'
      default_redirection_url: 'https://{{mustEnv "AUDIOBOOKSHELF_HOST"}}/'
      name: "abs_sess"
      same_site: "lax"
    - domain: {{mustEnv "OLLAMA_HOST"}}
      authelia_url: 'https://{{mustEnv "OLLAMA_HOST"}}/authelia'
      default_redirection_url: 'https://{{mustEnv "OLLAMA_HOST"}}/'
      name: "ollama_sess"
      same_site: "lax"
    - domain: {{mustEnv "NEXTCLOUD_HOST"}}              
      authelia_url: 'https://{{mustEnv "NEXTCLOUD_HOST"}}/authelia'
      default_redirection_url: 'https://{{mustEnv "NEXTCLOUD_HOST"}}/'
      name: "nc_sess"
      same_site: "lax"

authentication_backend:
  file:
    path: /config/users.yaml
    password:
      algorithm: argon2id

storage:
  local:
    path: /tmp/db.sqlite3  

notifier:
  filesystem:
    filename: /tmp/notification.log


access_control:
  default_policy: deny
  rules:
    - domain: {{mustEnv "AUDIOBOOKSHELF_HOST"}}
      policy: one_factor
      subject: ["group:audiobookshelf-users", "group:platform-admins"]
    - domain: {{mustEnv "OLLAMA_HOST"}}
      policy: one_factor
      subject: ["group:ollama-users", "group:platform-admins"]
    - domain: {{mustEnv "NEXTCLOUD_HOST"}}
      policy: one_factor   
      subject: ["group:platform-admins", "group:nextcloud-users"]

identity_providers:
  oidc:
    hmac_secret: '{{ fileContent "/secrets/oidc_hmac_secret" | trim }}'
    minimum_parameter_entropy: 16
    jwks:
      - key_id: "signing-rsa-2025-09"
        use: "sig"
        algorithm: "RS256"
        key: |
          {{ fileContent "/secrets/oidc_signing_private.pem" | nindent 10 }}
        certificate_chain: |
          {{ fileContent "/secrets/oidc_signing_public.crt" | nindent 10 }}


    lifespans:
      custom:
        nc_short:
          authorize_code: 5m
          access_token: 1h
          id_token: 30m

    clients:
      - client_id: nextcloud
        client_name: Nextcloud
        lifespan: nc_short
        client_secret: '{{ mustEnv "NC_CLIENT_SECRET" | trim }}'
        public: false

        redirect_uris:
          - https://nextcloud.neovara.uk/apps/user_oidc/callback
          - https://nextcloud.neovara.uk/index.php/apps/user_oidc/callback
          - https://nextcloud.neovara.uk/apps/user_oidc/code

        scopes: [openid, profile, email, groups]
        authorization_policy: one_factor
        token_endpoint_auth_method: client_secret_post
        require_pkce: true
        pkce_challenge_method: S256
        consent_mode: auto
