services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    network_mode: "host"

    environment:
      TZ: Asia/Tokyo
      FTLCONF_webserver_port: "8076"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

    restart: unless-stopped
